export default function Logo() {
  return (
    <svg
      width="344"
      height="52"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      fill="#ffffff"
      aria-labelledby="conf-logo-title-header"
    >
      <g id="Layer_1">
        <title>Layer 1</title>
        <text
          xmlSpace="preserve"
          textAnchor="start"
          fontFamily="'Archivo'"
          fontSize="52"
          id="svg_2"
          y="44.75"
          x="0"
          strokeWidth="0"
          stroke="#000000"
          fill="currentColor"
        >
          烘焙馆
        </text>
        <line
          strokeWidth="3"
          id="svg_3"
          y2="1.87501"
          x2="344"
          y1="2"
          x1="199"
          stroke="currentColor"
          fill="none"
        />
        <line
          strokeWidth="3"
          id="svg_4"
          y2="50"
          x2="344"
          y1="50"
          x1="200"
          stroke="currentColor"
          fill="none"
        />
        <text
          xmlSpace="preserve"
          textAnchor="start"
          fontFamily="'Archivo'"
          fontSize="29"
          id="svg_5"
          y="37.37499"
          x="198.49974"
          strokeWidth="0"
          stroke="#000000"
          fill="currentColor"
        >
          河畔花都店
        </text>
        <text
          transform="matrix(0.475293 0 0 0.498397 85.8959 33.2156)"
          stroke="#000000"
          xmlSpace="preserve"
          textAnchor="start"
          fontFamily="'Archivo'"
          fontSize="29"
          id="svg_6"
          y="34.12499"
          x="162.74976"
          strokeWidth="0"
          fill="currentColor"
        >
          巨野
        </text>
      </g>
    </svg>
  );
}
